### ISSUE TITLE
400 error: 'File does not exist'

### ISSUE THREAD

**Issue by sea4nl** [immich-app/CLI#106]
Hi! I'm looking to upload JPG files using the newest versions of immich and immich-CLI (just checked). However, I can't figure out what I'm doing wrong. Upload through the web app and the mobile app work. I'm using Immich on a web server behind Caddy, but even referencing the docker instance itself over port 2283 doesn't seem to work. I get the following error message:
```
user@thinkpad$ immich upload --key [key] --server [server]/api DSC_4780.JPG --import
Checking connectivity with Immich instance...
Server status: OK
Checking credentials...
Login status: OK
Successful authentication for user [user]
Indexing local assets...
Indexing complete, found 1 local assets
Comparing local assets with those on the Immich instance...
A total of 1 assets will be uploaded to the server
Do you want to start upload now? (y/n) y
Start uploading...
Upload Progress | ████████████████████████████████████████ | 100% || 1/]
Error asset:  {
  file: '/home/[user]/Pictures/DSC_4780.JPG',
  reason: Error: Request failed with status code 400
      at createError (/usr/lib/node_modules/immich/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/usr/lib/node_modules/immich/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/immich/node_modules/axios/lib/adapters/http.js:322:11)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1358:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      maxRedirects: 0,
      url: '[server]/api/asset/import',
      data: '{"deviceAssetId":"DSC_4780.JPG-13585281","deviceId":"cc9e70b663c1454dbb3ba7e4aa725cf3","assetType":"IMAGE","fileCreatedAt":"2023-07-20T20:52:24.570Z","fileModifiedAt":"2023-07-20T20:52:24.570Z","isFavorite":"false","fileExtension":".JPG","duration":"0:00:00.000000","isReadOnly":"true","assetPath":"/home/[user]/Pictures/DSC_4780.JPG"}'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 357,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /api/asset/import HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'x-api-key: qet0va080WikIlnK7KMIeHINg7ABXADmnvGxINfPww\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Content-Length: 357\r\n' +
        'Host: immich.stefbroenink.nl\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/asset/import',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'immich.stefbroenink.nl',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function: toJSON]
  },
  response: {
    statusCode: 400,
    message: 'File does not exist',
    error: 'Bad Request'
  }
}
```

**Comment by bo0tzz** [comment]
The --import flag is for the read-only gallery feature, which requires you to mount the files to the Immich containers.

**Comment by sea4nl** [comment]
I should learn to read better.. Thanks!
