### ISSUE TITLE
Missing Promises in npm package?

### ISSUE THREAD

**Issue by tristan-kirkpatrick** [immich-app/CLI#108]
Hi,

I've tried to run the CLI and getting the following error:

`internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/local/lib/node_modules/immich/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/immich/bin/index.js:48:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/immich/bin/index.js' ]
}`

**Comment by jrasm91** [comment]
This is a system package added in later version of nodejs. We use node 18. You can check your node version by running `node -v`.

**Comment by moll-re** [comment]
I don't think that is the issue. It has to do with current working directory misconfigurations (which I didn't bother inquiring)

I'm running on kubernetes, release `v1.71.0`, on the `immich-server` container, I run:

```
/usr/src/app/upload # immich --help
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/usr/src/app/upload/node_modules/immich/bin/index'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0
```
Which as you see has a sufficient node version.

Changing the `cwd` to the default one of the container:

```
/usr/src/app/upload # cd /usr/src/app
/usr/src/app # immich --help
Usage: immich [options] [command]

Immich command line interface

Options:
  -V, --version                output the version number
  -h, --help                   display help for command

Commands:
  upload [options] [paths...]  Upload assets to an Immich instance
  help [command]               display help for command

```
