### ISSUE TITLE
Error since version 0.14.0

### ISSUE THREAD

**Issue by MalteKiefer** [immich-app/CLI#12]
I updated to latest version, I get these error:

```
maltekiefer@MBP-von-Malte ~> yarn global add immich --force
yarn global v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Installed "immich@0.14.0" with binaries:
      - immich
✨  Done in 3.20s.
maltekiefer@MBP-von-Malte ~> immich upload --email xxx --password xxx --server https://xxxxx/api -d /Users/xxx/Export/ --yes
file:///Users/xxxxx/.config/yarn/global/node_modules/immich/bin/index.js:13
import pjson from "../package.json" assert { type: "json" };
                                    ^^^^^^

SyntaxError: Unexpected identifier
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:67:21)
```

**Comment by alextran1502** [comment]
Fixed in https://github.com/immich-app/CLI/releases/tag/v0.15.0
