### ISSUE TITLE
[Feature]: Bulk upload through watched folder

### ISSUE THREAD

**Issue by gdelosre91** [immich-app/CLI#18]
### Feature detail

Similar to photoprism, I'd love to be able to drop uploads in a specific watched folder. I'm running immich in a container on one of my servers, and I get images from all sorts of devices that don't necessarily run immich. I can then have a script that pushes these images from other servers to a folder that immich watches for upload.

### Platform

Server

**Comment by panoti** [comment]
Excuse me, I move this issue to correct repo for tracking.

**Comment by gdelosre91** [comment]
I'm now running into an issue where I'm trying to use this command on a folder with 2,750 photos. The command uploads ~ 100 before the process and docker container seem to stop.

**Comment by alextran1502** [comment]
Are you using the docker command or the normal cli command?

**Comment by gdelosre91** [comment]
I'm using the docker command:
`docker run -it --rm -v /media/share/photos/:/import ghcr.io/alextran1502/immich-cli:latest upload --email test@test.com --password pw12344 --server http://192.168.4.32:2283/api -d /import`

**Comment by gdelosre91** [comment]
It's worth noting that /media/share is a mounted SMB share

**Comment by gdelosre91** [comment]
I tried the normal CLI command and it produced this error:
```
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /usr/local/lib/node_modules/immich/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/immich/bin/index.js:48:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/immich/bin/index.js' ]
}
```

**Comment by alextran1502** [comment]
I think it is your node version issue. Can you make sure you are using Node v16 and above?

**Comment by gdelosre91** [comment]
Looks like that worked, thanks!

**Comment by gdelosre91** [comment]
Bit of a noob here, but is there any way to use a cron job to automate the CLI script? where I get stuck is that i know the script does ask you if you would like to upload now. how you would you automate that?

**Comment by gdelosre91** [comment]
Answered my own question by actually reading the documentation lol 

I'll append `--yes / -y`
