### ISSUE TITLE
Error: Request failed with status code 504

### ISSUE THREAD

**Issue by Backslashh** [immich-app/CLI#20]
I'm uploading about 400 assets using the docker method and keep running into this error:
Error uploading asset [/import/20220815_065326_9A9FEC1A.mov]: Error: Request failed with status code 504

This happens for quite a few items. If I run it again, the errored assets seems to be less and less. 

At the point now where I run the job and it tells me there are two assets to upload, and it seems to do so without error, however whenever I run the job, it says the same thing over and over.

![image](https://user-images.githubusercontent.com/2252680/188780058-91635293-6eb3-4aa5-b21e-41b490f83b82.png)

**Comment by alextran1502** [comment]
Is this issue still persist with the latest version of the server 1.28.3?

**Comment by Backslashh** [comment]
It seems to have fixed the 504 error, I am still getting the app telling me it needs to upload the same assets over and over. 
It runs and uploads all assets without error, and then if I run it again over the same folder, it says I need to upload the same amount again.

**Comment by alextran1502** [comment]
I assume those are duplicated asset. The duplication assets failed silently. We haven't update the CLI yet to reflect the duplicated error code

**Comment by Backslashh** [comment]
Ah okay I understand. So it'll always say there is the same amount of assets to upload as the previous run.
Like this:
![image](https://user-images.githubusercontent.com/2252680/190034382-10fb10c1-0b1d-467b-a836-6aa897c26ebc.png)

**Comment by alextran1502** [comment]
Pretty crazy that you have that many duplicated. To make sure those are duplicated you can monitor the server log to see if the error message popped up.

**Comment by Backslashh** [comment]
That's what I mean, I don't believe they are duplicated assets.

**Comment by alextran1502** [comment]
Did you see anything while uploading in the server logs?

**Comment by alextran1502** [comment]
Logs write to console, you can use this command https://docs.docker.com/engine/reference/commandline/logs/

The log for inserting will be in the immich-server container

**Comment by Backslashh** [comment]
I'm not seeing any logs relating to duplicates.
![image](https://user-images.githubusercontent.com/2252680/190039066-d31636cd-3191-4dc8-b54b-6f8fcac55428.png)

**Comment by alextran1502** [comment]
hmm strange. Time to rewrite CLI tool

**Comment by Backslashh** [comment]
Just got another 504 error too.
![image](https://user-images.githubusercontent.com/2252680/190052398-59ede469-9059-49f8-b189-856b3dc86c5e.png)

**Comment by alextran1502** [comment]
Ok! I will need to add better error message to handle these cases. Would you mind tell me how big is the video file?

**Comment by Backslashh** [comment]
Sure!
The file is 1.49GB in size and the upload is happening locally. No proxies involved.

**Comment by seriousm4x** [comment]
Same for me. My file is 2.5G
```node
Failed to upload 1 files  [
  {
    file: 'Z:\\Bilder\\xxxx.xx - iPhone\\IMG_0177.MOV',
    reason: Error: Request failed with status code 504
        at createError (C:\Users\max\AppData\Local\pnpm\global\5\.pnpm\axios@0.26.1\node_modules\axios\lib\core\createError.js:16:15)
        at settle (C:\Users\max\AppData\Local\pnpm\global\5\.pnpm\axios@0.26.1\node_modules\axios\lib\core\settle.js:17:12)
        at IncomingMessage.handleStreamEnd (C:\Users\max\AppData\Local\pnpm\global\5\.pnpm\axios@0.26.1\node_modules\axios\lib\adapters\http.js:322:11)
        at IncomingMessage.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
      config: [Object],
      request: [ClientRequest],
      response: [Object],
      isAxiosError: true,
      toJSON: [Function: toJSON]
    },
    response: '<html>\r\n' +
      '<head><title>504 Gateway Time-out</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
      '<hr><center>nginx/1.23.3</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  }
]
```
