### ISSUE TITLE
Question: can this run on arm64?

### ISSUE THREAD

**Issue by jpmiller25** [immich-app/CLI#23]
Hello, I'm trying to run this utility on Rpi4 with ubuntu server 22.04.5. When installing immich I get a lot of dependency warnings "SKIPPING OPTIONAL DEPENDENCIES" and then when I run the command I get:
`Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/immich/bin/index.js:48:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

I'm guessing this is a dependency issue and if I tried to run on amd64 it would run fine?

**Comment by alextran1502** [comment]
Please update your nodejs version to at least v16

**Comment by jpmiller25** [comment]
That was it, thank you!
