### ISSUE TITLE
Error 400 to upload images

### ISSUE THREAD

**Issue by TonioDF** [immich-app/CLI#65]
Hello, can someone tell me what is causing this error?  I have been uploading photos without any problem and since the last update it gives me this error un allo files: 

file: '/import/CAM00395.jpg',
    reason: Error: Request failed with status code 400
        at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:322:11)
        at IncomingMessage.emit (node:events:539:35)
        at endReadableNT (node:internal/streams/readable:1345:12)                                                                     at processTicksAndRejections (node:internal/process/task_queues:83:21) {                                                    config: [Object],
      request: [ClientRequest],
      response: [Object],
      isAxiosError: true,
      toJSON: [Function: toJSON]
    },
    response: { statusCode: 400, message: [Array], error: 'Bad Request' }         # #

Thanks !!

**Comment by alextran1502** [comment]
@TonioDF have you updated your CLI tool to the latest version?

**Comment by bo0tzz** [comment]
Have you updated the CLI to the latest version as well?

**Comment by TonioDF** [comment]
I use the command indicated, with the image "latest".
`docker run -it --rm -v /DIRECTORY/WITH/IMAGES:/import ghcr.io/immich-app/immich-cli:latest upload --key HFEJ38DNSDUEG --server http://192.168.1.216:2283/api`

I use this docker rm with my ip and API..etc

I am doing something wrong ??

**Comment by bo0tzz** [comment]
If you've already used the CLI before, using `:latest` may not actually use the newest version of the image, since some version is already present on your machine. Try running `docker pull ghcr.io/immich-app/immich-cli:latest` to update it.

**Comment by TonioDF** [comment]
@bo0tzz thanks !!!
Yes, that was the problem, now it hasn't given me any errors.  Sorry for my ignorance, I didn't know this could happen.
