### ISSUE TITLE
Upload failing with big files

### ISSUE THREAD

**Issue by jagjordi** [immich-app/CLI#66]
Server version: v1.50.1
CLI version: latest (using docker)

I upload a large MP4 file (~4GB) and it fails with the following error:
```
Upload Progress | ████████████████████████████████████████ | 100% || 1/1 || Current file [/import/GH010391.MP4]
Failed to upload 1 files  [
  {
    file: '/import/GH010391.MP4',
    reason: Error: Request failed with status code 413
        at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
        at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)
        at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:322:11)
        at IncomingMessage.emit (node:events:539:35)
        at endReadableNT (node:internal/streams/readable:1345:12)
        at processTicksAndRejections (node:internal/process/task_queues:83:21) {
      config: [Object],
      request: [ClientRequest],
      response: [Object],
      isAxiosError: true,
      toJSON: [Function: toJSON]
    },
    response: '<html>\r\n' +
      '<head><title>413 Request Entity Too Large</title></head>\r\n' +
      '<body>\r\n' +
      '<center><h1>413 Request Entity Too Large</h1></center>\r\n' +
      '<hr><center>openresty</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  }
]
```
If I try with a smaller file, it works. Any ide on why this happens?
Thanks!

**Comment by bo0tzz** [comment]
Your reverse proxy is rejecting it because the body is too large. You need to set `client_max_body_size` in the nginx configuration, or the equivalent for whatever proxy you're using.
