### ISSUE TITLE
ENOENT: no such file or directory with broken emojis in file names

### ISSUE THREAD

**Issue by rathmerdominik** [immich-app/CLI#81]
OS: Archlinux

Background information:
- The files have been pulled from my phone with `android-file-transfer` 
- I tried to upload them with the command `immich upload --key <apikey> --server http://192.168.2.x:2283/api --recursive Internal\ shared\ storage/`

Result:

```Checking connectivity with Immich instance...
Server status: OK
Checking credentials...
Login status: OK
Successful authentication for user rathmerdominik@outlook.de
Indexing local assets...
node:fs:1619
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, stat '/home/dominik/Internal shared storage/Movie

https://user-images.githubusercontent.com/13904508/236698282-310b3c95-eefc-470c-840b-eb5a458119a9.mp4

s/Don_t need to work at McDonald_s if you invest in #DigiByte ������.mp4'
    at Object.statSync (node:fs:1619:3)
    at /usr/lib/node_modules/immich/bin/index.js:176:37
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/immich/bin/index.js:29:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/home/dominik/Internal shared storage/Movies/Don_t need to work at McDonald_s if you invest in #DigiByte ������.mp4'
}

Node.js v19.9.0
```

You also see the � that indicates corrupted characters. I have noto-fonts-emoji installed and emojis are normally completely visible on my system.

Interestingly those files also have that corrupted character when viewed through ls.
![image](https://user-images.githubusercontent.com/13904508/236698014-22ed5cae-38c1-4a8f-8dcb-d8c1870b25da.png)

The file obviously has bad encoding in the filename that apparently no font can solve. the entire noto-fonts suite does not have a suitable font for this so does ttf-droid.
![image](https://user-images.githubusercontent.com/13904508/236698330-392f6836-1cb5-4815-8f46-e3dcfc7deca9.png)

Maybe the program should add an option to just skip and log the broken files it found?
This would be far better than it just crashing.

![image](https://user-images.githubusercontent.com/13904508/236698418-620191b3-46c4-417d-add6-d0047fe47ba1.png)

This is what the filename should look like originally.

**Comment by rathmerdominik** [comment]
Is now solved with the merge of #83 :+1:
