### ISSUE TITLE
upload failed when uploading large video files

### ISSUE THREAD

**Issue by ycao56** [immich-app/CLI#87]
I found when using CLI to upload large video files it fails. Tried a few video files with 700mb, 1gb.
```
  {
    file: '/import/2017-12-20 14.09.19.MOV',
    reason: Error: error request aborted
        at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
        at IncomingMessage.handlerStreamAborted (/usr/src/app/node_modules/axios/lib/adapters/http.js:301:18)
        at IncomingMessage.emit (node:events:527:28)
        at IncomingMessage._destroy (node:_http_incoming:179:10)
        at _destroy (node:internal/streams/destroy:102:25)
        at IncomingMessage.destroy (node:internal/streams/destroy:64:5)
        at Socket.socketCloseListener (node:_http_client:414:11)
        at Socket.emit (node:events:539:35)
        at TCP.<anonymous> (node:net:709:12) {
      config: [Object],
      code: 'ERR_REQUEST_ABORTED',
      request: [ClientRequest],
      response: undefined,
      isAxiosError: true,
      toJSON: [Function: toJSON]
    },
    response: undefined
  }
```

**Comment by wiseindy** [comment]
Yeah I'm having the same issue as you - https://github.com/immich-app/CLI/issues/86. It succeeds for me occasionally, but the larger the file, the higher the chance it is going to fail.
